export const LANG_TH_TRANS = {
    'this_email_already_used': 'อีเมลนี้ถูกใช้งานแล้ว',
    'authen_failed': 'ตรวจสอบสิทธิ์ล้มเหลว',
    'unknown_error': 'ไม่สามารถระบุความผิดพลาดได้',
    'invalid_username_or_password': 'ชื่อผู้ใช้งานหรือรหัสผ่านไม่ถูกต้อง',
    'token_not_saved': 'Token not saved.',
    'invalid_user': 'Invalid user.',
    'user_not_verified': 'บัญชีผู้ใช้งานนี้ยังไม่ได้ทำการยืนยันตัวตน',
    'unauthorized': 'ไม่มีสิทธิ์ในการเข้าถึงข้อมูล',
    'user_not_found': 'ไม่พบข้อมูลผู้ใช้งาน',
    'invalid_password': 'Invalid password.',
    'client_not_found': 'Clinet not found.',
    'address_not_found': 'ไม่พบข้อมูลที่อยู่',
    'token_expired': 'token หมดอายุการใช้งาน',
    'barcode_not_enough': 'จำนวนบาร์โค้ดคงเหลือในระบบไม่เพียงพอ',
    'barcode_service_not_found': 'ไม่พบข้อมูลบาร์โค้ดตามประเภทบริการ',
    'invalid_activate_key': 'รหัสยืนยันตัวตนไม่ถูกต้อง',
    'this_user_already_activate': 'ผู้ใช้งานนี้ได้ทำการยืนยันตัวตนเรียบร้อยแล้ว',
    'reserve_already_confirm': 'รหัสการจองนี้ได้ทำการยืนยันเรียบร้อยแล้ว',
    'service_type_not_found': 'ไม่พบรหัสบริการ',
    'confirm_email_subject': 'ยืนยันการสมัครสมาชิกระบบ Prompt Post',
    'confirm_email_title': 'ยินดีต้อนรับสู่ระบบ Prompt Post',
    'confirm_email_message': 'กรุณายืนยันตัวตนเพื่อเริ่มใช้งาน ระบบ Prompt Post ของคุณ',
    'confirm_email_button': 'ยืนยันตัวตน',
    'forgot_password_subject': 'ตั้งค่ารหัสผ่านใหม่ระบบ Prompt Post', 
    'forgot_password_message': 'คลิกที่ปุ่มด้านล่างเพื่อทำการตั้งค่ารหัสผ่านใหม่',
    'forgot_password_button': 'ตั้งค่ารหัสผ่านใหม่',  
};